-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >= TO_DATE('20220301', 'YYYYMMDD')
  AND SALES_DATE < TO_DATE('20220401', 'YYYYMMDD')

UNION ALL

SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >= TO_DATE('20220301', 'YYYYMMDD')
  AND SALES_DATE < TO_DATE('20220401', 'YYYYMMDD')
  
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC