-- 코드를 입력하세요
WITH RENTAL AS (
    SELECT
        H.HISTORY_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        H.END_DATE - H.START_DATE + 1 AS RENT_DAYS
    FROM CAR_RENTAL_COMPANY_CAR C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT
    R.HISTORY_ID,
    TRUNC(
        R.DAILY_FEE
        * R.RENT_DAYS
        * (100 - NVL(P.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM RENTAL R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON R.CAR_TYPE = P.CAR_TYPE
   AND P.DURATION_TYPE =
        CASE
            WHEN R.RENT_DAYS >= 90 THEN '90일 이상'
            WHEN R.RENT_DAYS >= 30 THEN '30일 이상'
            WHEN R.RENT_DAYS >= 7 THEN '7일 이상'
        END
ORDER BY FEE DESC, R.HISTORY_ID DESC;