-- 코드를 작성해주세요
SELECT
    EC.ID
    , EC.GENOTYPE
    , EP.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA EC
INNER JOIN ECOLI_DATA EP ON (EC.PARENT_ID = EP.ID)
WHERE (EC.GENOTYPE & EP.GENOTYPE) = EP.GENOTYPE
ORDER BY ID ASC;