-- 코드를 입력하세요
SELECT MCDP_CD AS "진료과 코드", COUNT(MCDP_CD) AS "5월예약건수"
FROM APPOINTMENT
WHERE APNT_YMD >= TO_DATE('2022-05-01', 'YYYY-MM-DD')
  AND APNT_YMD < TO_DATE('2022-06-01', 'YYYY-MM-DD')
GROUP BY MCDP_CD
ORDER BY "5월예약건수" ASC, "진료과 코드" ASC;

