-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D INNER JOIN HR_EMPLOYEES E ON (D.DEPT_ID = E.DEPT_ID)
                     INNER JOIN HR_GRADE G ON (E.EMP_NO = G.EMP_NO)
WHERE G.YEAR = 2022
GROUP BY EMP_NO, EMP_NAME, POSITION, EMAIL
ORDER BY SCORE DESC
LIMIT 1;